sudo: required
services:
 -docker

before_install: 
  -docker build -t sanusatyadarshi/docker-react -f Dockerfile.dev .

script:
  -docker run sanusatyadarshi/docker-react npm run test -- --coverage
  
